apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fah
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fah
        tier: backend
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: fah
        image: de.icr.io/firstaid/firstaidhelper:5
        imagePullPolicy: Always
        ports:
         - name: http
           containerPort: 8080
        env:
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: mongo-credentials
                key: host 
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: mongo-credentials
                key: port         
          - name: MONGO_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mongo-credentials
                key: database 
          - name: MONGO_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongo-credentials
                key: username 
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: firstaid-dev-mongodb
                key: mongodb-password
---
apiVersion: v1
kind: Service
metadata:
  name: fah
  labels:
    app: fah
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
    nodePort: 31238
  selector:
    app: fah